### ISSUE TITLE
Intrested in contribution

### ISSUE THREAD

**Issue by Kanha-13** [iskitsas/http-traffic-simulator#4]
Hi, I am Kanha Agrawal a full stack MERN developer from India. I am in the pre-final year of a Computer Science Degree. Looking forward to contributing to this project via GSOC 2022. Please guide me to where to start with.
Thank you.

**Comment by iskitsas** [comment]
See the instructions [here](https://ellak.gr/wiki/index.php?title=Google_Summer_of_Code_2022_proposed_ideas) and focus on this [repo](https://github.com/flexivian/flexbench).

In general subscribe to the emailing list provided in the first url, to ask any questions, and you can start looking for good-first-issues on the new repo

**Comment by Kanha-13** [comment]
Thank you for the reply, I will start with the good first issue.
